
 <div class="sidebar-header border border-success ">
                <img src="../assets/img/Logo.png" alt="" class="w-100 h-100 ">
            </div>

            <ul class="list-unstyled components">
                <p> Módulo interno</p>
            

                <li class="">
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-industry"> Empresas </i></a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="intuser.php"><i class="fas fa-key"></i> Usuarios internos EM </a>
                        </li>
                        <li>
                            <a href="comerc.php"><i class="fas fa-industry"></i> Comercializadores   </a>
                        </li>
                        <li>
                            <a href="transbot.php"><i class="fas fa-wrench"></i> Transacciones Bot </a>
                        </li>
                        <li>
                            <a href="historicos.php"><i class="fas fa-history"></i> Registro Consumos Históricos </a>
                        </li>
                        <li>
                            <a href="anulaciones.php"><i class="fas fa-ban"></i> Control de errores </a>
                            
                        </li>
                        <li>
                            <a href="modgob.php"><i class="fas fa-user"></i> <i class="fas fa-sitemap"></i> Modelo de gobierno </a>
                            
                        </li>
                         <li>
                            <a href="testftp.php"><i class="fas fa-user"></i> <i class="fas fa-sitemap"></i> pruebas </a>
                            
                        </li>

                    
                    </ul>
                </li>
                <li>
                    <a href="https://energymaster.app/index.php/index " target="_blank" >Energyapp</a>
                </li>
                <li>
                    <a href="https://energyhome.azurewebsites.net/index.php/index " target="_blank" >EnergyHome</a>
                </li>
               
                <li class="">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-users"></i>  Colaboradores </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="formulario.php"><i class="fas fa-user"></i> <i class="fas fa-list"></i>  Datos personales colaboradores</a>
                        </li>
                      
                    </ul>

                    <a href="cerrarsesion.php" class="text-danger  btn btn-warning">Cerrar sesion</a> 