<nav class="navbar navbar-expand-lg navbar-light ">

    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>
            <span>Menú</span>
        </button>

    </div>

</nav>
<div class="container-fluid col-10 text-center imgs mt-2  formulario1">


    <h1 class="verde titulos ">Pagina deshabilitada</h1>



    <section class="row justify-content-center p-3">



        <div class="jumbotron display-1">
            <p>404 pagina no disponible</p>
           <a href="cerrarsesion.php" class="text-danger btn btn-warning">Cerrar sesion</a>
        </div>




    </section>




</div>